import { NavLink, BlogPost, Topic } from './types';

export const NAV_LINKS: NavLink[] = [
  { label: 'Home', href: '#home' },
  { label: 'Offensive', href: '#offensive' },
  { label: 'SOC', href: '#soc' },
  { label: 'GRC', href: '#grc' },
  { label: 'Products', href: '#products' },
  { label: 'AI Security', href: '#ai' },
];

export const HERO_STATS = [
  { value: '50+', label: 'Articles' },
  { value: '5', label: 'Topics' },
  { value: '1K+', label: 'Readers' },
];

export const SECURITY_TOPICS: Topic[] = [
  {
    id: 'siem',
    title: 'SIEM',
    shortDescription: 'Security Information and Event Management',
    fullDescription: 'SIEM software products and services combine security information management (SIM) and security event management (SEM). They provide real-time analysis of security alerts generated by applications and network hardware.',
    icon: '📊'
  },
  {
    id: 'xdr',
    title: 'XDR',
    shortDescription: 'Extended Detection and Response',
    fullDescription: 'XDR is a SaaS-based, vendor-specific, security threat detection and incident response tool that natively integrates multiple security products into a cohesive security operations system.',
    icon: '🛡️'
  },
  {
    id: 'soar',
    title: 'SOAR',
    shortDescription: 'Security Orchestration, Automation and Response',
    fullDescription: 'SOAR refers to a stack of compatible software programs that allow an organization to collect data about security threats from multiple sources and respond to low-level security events without human assistance.',
    icon: '🤖'
  },
  {
    id: 'pentest',
    title: 'Pentesting',
    shortDescription: 'Offensive Security & Ethical Hacking',
    fullDescription: 'Penetration testing involves simulating cyberattacks on your computer system to check for exploitable vulnerabilities. It is a core component of offensive security strategies.',
    icon: '⚔️'
  }
];

export const LATEST_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'Implementing Wazuh as an Open Source SIEM',
    excerpt: 'A comprehensive guide to setting up Wazuh for threat detection, integrity monitoring, and incident response in a small enterprise environment.',
    category: 'SOC',
    date: 'Oct 24, 2023',
    readTime: '8 min read',
    tags: ['Wazuh', 'SIEM', 'Open Source']
  },
  {
    id: '2',
    title: 'The Rise of AI-Powered Phishing',
    excerpt: 'How Large Language Models are being used to create sophisticated phishing campaigns and what defense mechanisms can be deployed.',
    category: 'AI Security',
    date: 'Oct 28, 2023',
    readTime: '5 min read',
    tags: ['LLM', 'Phishing', 'Defense']
  },
  {
    id: '3',
    title: 'Automating Incident Response with SOAR',
    excerpt: 'Reduce alert fatigue by automating repetitive tasks. We explore how to build playbooks for common security alerts.',
    category: 'SOC',
    date: 'Nov 02, 2023',
    readTime: '12 min read',
    tags: ['Automation', 'Playbooks', 'Efficiency']
  }
];
